"""add wallet system tables

Revision ID: 75d679f44f25
Revises: aa37b2c24ef8
Create Date: 2026-08-13 08:48:42.192275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d679f44f25'
down_revision: Union[str, Sequence[str], None] = 'aa37b2c24ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('remaining_toman', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('reminder_30d_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_7d_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_1d_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_wallet_charges_payment_id_payments')),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_wallet_charges_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_charges'))
    )
    op.create_index(op.f('ix_wallet_charges_shop_owner_id'), 'wallet_charges', ['shop_owner_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('wallet_charge_id', sa.Integer(), nullable=True),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_wallet_transactions_shop_owner_id_shop_owners')),
    sa.ForeignKeyConstraint(['wallet_charge_id'], ['wallet_charges.id'], name=op.f('fk_wallet_transactions_wallet_charge_id_wallet_charges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions'))
    )
    op.create_index(op.f('ix_wallet_transactions_shop_owner_id'), 'wallet_transactions', ['shop_owner_id'], unique=False)
    op.add_column('admin_settings', sa.Column('wallet_topup_validity_months', sa.Integer(), nullable=False, server_default='12'))
    op.add_column('admin_settings', sa.Column('wallet_cost_per_1k_tokens_toman', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('admin_settings', sa.Column('wallet_cost_photo_analysis_toman', sa.Integer(), nullable=False, server_default='500'))
    op.add_column('admin_settings', sa.Column('wallet_cost_voice_transcription_toman', sa.Integer(), nullable=False, server_default='300'))
    op.add_column('admin_settings', sa.Column('wallet_cost_order_detection_toman', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('admin_settings', sa.Column('wallet_low_balance_warning_toman', sa.Integer(), nullable=False, server_default='20000'))
    op.add_column('payments', sa.Column('purpose', sa.String(length=32), nullable=False, server_default='subscription'))
    op.alter_column('payments', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('shop_owners', sa.Column('wallet_balance_toman', sa.Integer(), nullable=False, server_default='0'))

    # همون الگویی که برای zarinpal_enabled یاد گرفتیم: server_default فقط برای
    # backfillِ ردیف‌های موجود لازمه؛ بعدش پاکش می‌کنیم که با مدلِ ORM (که فقط
    # default سمتِ پایتون داره، نه server_default) هم‌خوان بمونه و alembic check
    # درصدِ اختلافِ کاذب گزارش نده.
    for table, column in [
        ('admin_settings', 'wallet_topup_validity_months'),
        ('admin_settings', 'wallet_cost_per_1k_tokens_toman'),
        ('admin_settings', 'wallet_cost_photo_analysis_toman'),
        ('admin_settings', 'wallet_cost_voice_transcription_toman'),
        ('admin_settings', 'wallet_cost_order_detection_toman'),
        ('admin_settings', 'wallet_low_balance_warning_toman'),
        ('payments', 'purpose'),
        ('shop_owners', 'wallet_balance_toman'),
    ]:
        op.alter_column(table, column, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_owners', 'wallet_balance_toman')
    op.alter_column('payments', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'purpose')
    op.drop_column('admin_settings', 'wallet_low_balance_warning_toman')
    op.drop_column('admin_settings', 'wallet_cost_order_detection_toman')
    op.drop_column('admin_settings', 'wallet_cost_voice_transcription_toman')
    op.drop_column('admin_settings', 'wallet_cost_photo_analysis_toman')
    op.drop_column('admin_settings', 'wallet_cost_per_1k_tokens_toman')
    op.drop_column('admin_settings', 'wallet_topup_validity_months')
    op.drop_index(op.f('ix_wallet_transactions_shop_owner_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_charges_shop_owner_id'), table_name='wallet_charges')
    op.drop_table('wallet_charges')
    # ### end Alembic commands ###
