"""add referral reward wallet toman

Revision ID: 7b7447577287
Revises: ef582d0ccfc5
Create Date: 2026-08-14 10:14:33.709764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7447577287'
down_revision: Union[str, Sequence[str], None] = 'ef582d0ccfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('admin_settings', sa.Column('referral_reward_wallet_toman', sa.Integer(), nullable=False, server_default='20000'))
    op.alter_column('admin_settings', 'referral_reward_wallet_toman', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_settings', 'referral_reward_wallet_toman')
    # ### end Alembic commands ###
