"""initial schema

Revision ID: e59de9fae404
Revises: 
Create Date: 2026-08-10 07:22:56.804765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59de9fae404'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sms_api_key', sa.Text(), nullable=True),
    sa.Column('ai_api_key', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('ai_base_url', sa.String(length=255), nullable=False),
    sa.Column('zarinpal_merchant_id', sa.String(length=64), nullable=True),
    sa.Column('platform_card_number', sa.String(length=32), nullable=True),
    sa.Column('platform_card_holder_name', sa.String(length=255), nullable=True),
    sa.Column('referral_reward_type', sa.String(length=32), nullable=False),
    sa.Column('referral_reward_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grace_period_hours', sa.Integer(), nullable=False),
    sa.Column('rate_limit_max_messages', sa.Integer(), nullable=False),
    sa.Column('rate_limit_window_seconds', sa.Integer(), nullable=False),
    sa.Column('payment_reservation_minutes', sa.Integer(), nullable=False),
    sa.Column('periodic_report_frequency_days', sa.Integer(), nullable=False),
    sa.Column('conversation_history_limit', sa.Integer(), nullable=False),
    sa.Column('knowledge_items_limit', sa.Integer(), nullable=False),
    sa.Column('global_ai_system_prompt', sa.Text(), nullable=True),
    sa.Column('reference_channel_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_settings'))
    )
    op.create_table('discount_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_discount_codes_code'))
    )
    op.create_table('mandatory_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invite_link', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandatory_channels')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_mandatory_channels_channel_id'))
    )
    op.create_table('shop_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('registration_completed', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['shop_owners.id'], name=op.f('fk_shop_owners_referred_by_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_owners')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_shop_owners_referral_code'))
    )
    op.create_index(op.f('ix_shop_owners_telegram_id'), 'shop_owners', ['telegram_id'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('duration_months', name=op.f('uq_subscription_plans_duration_months'))
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_otp_codes_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_shop_owner_id'), 'otp_codes', ['shop_owner_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Integer(), nullable=False),
    sa.Column('final_amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=255), nullable=True),
    sa.Column('discount_code_id', sa.Integer(), nullable=True),
    sa.Column('zarinpal_authority', sa.String(length=64), nullable=True),
    sa.Column('zarinpal_ref_id', sa.String(length=64), nullable=True),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], name=op.f('fk_payments_discount_code_id_discount_codes')),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_payments_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_shop_owner_id'), 'payments', ['shop_owner_id'], unique=False)
    op.create_index(op.f('ix_payments_zarinpal_authority'), 'payments', ['zarinpal_authority'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('reward_status', sa.String(length=32), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['shop_owners.id'], name=op.f('fk_referrals_referred_id_shop_owners')),
    sa.ForeignKeyConstraint(['referrer_id'], ['shop_owners.id'], name=op.f('fk_referrals_referrer_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('referred_id', name=op.f('uq_referrals_referred_id'))
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('shop_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('bot_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_username', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret_token', sa.String(length=64), nullable=False),
    sa.Column('ai_instructions', sa.Text(), nullable=True),
    sa.Column('zarinpal_merchant_id', sa.String(length=64), nullable=True),
    sa.Column('knowledge_channel_id', sa.String(length=64), nullable=True),
    sa.Column('knowledge_channel_bot', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('last_report_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_shop_bots_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_bots')),
    sa.UniqueConstraint('bot_telegram_id', name=op.f('uq_shop_bots_bot_telegram_id')),
    sa.UniqueConstraint('shop_owner_id', name=op.f('uq_shop_bots_shop_owner_id'))
    )
    op.create_index(op.f('ix_shop_bots_knowledge_channel_id'), 'shop_bots', ['knowledge_channel_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_reminder_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_subscriptions_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_shop_owner_id'), 'subscriptions', ['shop_owner_id'], unique=False)
    op.create_table('bot_error_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_bot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_bot_id'], ['shop_bots.id'], name=op.f('fk_bot_error_events_shop_bot_id_shop_bots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_error_events'))
    )
    op.create_index(op.f('ix_bot_error_events_shop_bot_id'), 'bot_error_events', ['shop_bot_id'], unique=False)
    op.create_table('channel_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_bot_id', sa.Integer(), nullable=False),
    sa.Column('source_channel_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_bot_id'], ['shop_bots.id'], name=op.f('fk_channel_knowledge_shop_bot_id_shop_bots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_knowledge'))
    )
    op.create_index(op.f('ix_channel_knowledge_shop_bot_id'), 'channel_knowledge', ['shop_bot_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_bot_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_bot_id'], ['shop_bots.id'], name=op.f('fk_customers_shop_bot_id_shop_bots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('shop_bot_id', 'telegram_id', name=op.f('uq_customers_shop_bot_id'))
    )
    op.create_index(op.f('ix_customers_shop_bot_id'), 'customers', ['shop_bot_id'], unique=False)
    op.create_table('discount_code_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=False),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], name=op.f('fk_discount_code_usages_discount_code_id_discount_codes')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_discount_code_usages_payment_id_payments')),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['shop_owners.id'], name=op.f('fk_discount_code_usages_shop_owner_id_shop_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_code_usages')),
    sa.UniqueConstraint('discount_code_id', 'shop_owner_id', name=op.f('uq_discount_code_usages_discount_code_id'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('photo_file_id', sa.String(length=255), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_bot_id'], ['shop_bots.id'], name=op.f('fk_products_shop_bot_id_shop_bots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_shop_bot_id'), 'products', ['shop_bot_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversation_messages_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index(op.f('ix_conversation_messages_customer_id'), 'conversation_messages', ['customer_id'], unique=False)
    op.create_table('orders_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_bot_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('estimated_value_toman', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_consultations_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_consultations_product_id_products')),
    sa.ForeignKeyConstraint(['shop_bot_id'], ['shop_bots.id'], name=op.f('fk_orders_consultations_shop_bot_id_shop_bots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_consultations'))
    )
    op.create_index(op.f('ix_orders_consultations_customer_id'), 'orders_consultations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_consultations_shop_bot_id'), 'orders_consultations', ['shop_bot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_consultations_shop_bot_id'), table_name='orders_consultations')
    op.drop_index(op.f('ix_orders_consultations_customer_id'), table_name='orders_consultations')
    op.drop_table('orders_consultations')
    op.drop_index(op.f('ix_conversation_messages_customer_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_products_shop_bot_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('discount_code_usages')
    op.drop_index(op.f('ix_customers_shop_bot_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_channel_knowledge_shop_bot_id'), table_name='channel_knowledge')
    op.drop_table('channel_knowledge')
    op.drop_index(op.f('ix_bot_error_events_shop_bot_id'), table_name='bot_error_events')
    op.drop_table('bot_error_events')
    op.drop_index(op.f('ix_subscriptions_shop_owner_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_shop_bots_knowledge_channel_id'), table_name='shop_bots')
    op.drop_table('shop_bots')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_payments_zarinpal_authority'), table_name='payments')
    op.drop_index(op.f('ix_payments_shop_owner_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_otp_codes_shop_owner_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_shop_owners_telegram_id'), table_name='shop_owners')
    op.drop_table('shop_owners')
    op.drop_table('mandatory_channels')
    op.drop_table('discount_codes')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
