"""add wallet trial credit and notification tracking

Revision ID: ef582d0ccfc5
Revises: 75d679f44f25
Create Date: 2026-08-13 09:09:17.461526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef582d0ccfc5'
down_revision: Union[str, Sequence[str], None] = '75d679f44f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('admin_settings', sa.Column('wallet_trial_credit_toman', sa.Integer(), nullable=False, server_default='50000'))
    op.add_column('shop_owners', sa.Column('wallet_low_balance_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shop_owners', sa.Column('wallet_empty_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('admin_settings', 'wallet_trial_credit_toman', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_owners', 'wallet_empty_notified_at')
    op.drop_column('shop_owners', 'wallet_low_balance_notified_at')
    op.drop_column('admin_settings', 'wallet_trial_credit_toman')
    # ### end Alembic commands ###
